#pragma once

using namespace ATL;

template <class T>
class CProxy_IMapiFolderWrpEvents : public IConnectionPointImpl<T, &__uuidof( _IMapiFolderWrpEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
